[forest]
trees = ["/home/kellen/Projects/forest/trees"]                   # The directories in which your trees are stored
assets = ["assets"]                  # The directories in which your assets are stored
home = "0001"
url = "https://kellenkanarios.com/"
