#!/usr/bin/env python3
import os
import subprocess
from http.server import BaseHTTPRequestHandler, HTTPServer
from urllib.parse import urlparse, parse_qs

SOCK = os.environ.get('NVIM_SOCK', '/tmp/nvim-forest.sock')
PORT = int(os.environ.get('FOPEN_PORT', '1235'))
WIN_TITLE = 'forest-fserve'
TMUX_SESSION = 'forest'
TMUX_EDIT_WINDOW = 'edit'

LAST_SLUG = [None]


def focus_or_spawn_alacritty():
    rc = subprocess.run(['wmctrl', '-a', WIN_TITLE],
                        capture_output=True).returncode
    if rc != 0:
        subprocess.Popen(
            ['alacritty', '-t', WIN_TITLE, '-e',
             'tmux', 'attach', '-t', TMUX_SESSION],
            start_new_session=True,
        )


class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        u = urlparse(self.path)
        q = parse_qs(u.query)

        if u.path == '/open':
            path = q.get('path', [''])[0]
            if not path:
                self._send(400, b'missing path'); return
            if not os.path.exists(SOCK):
                self._send(503, b'nvim socket not ready'); return
            subprocess.run(['nvim', '--server', SOCK, '--remote', path],
                           check=False)
            subprocess.run(['tmux', 'select-window', '-t',
                            f'{TMUX_SESSION}:{TMUX_EDIT_WINDOW}'],
                           check=False)
            focus_or_spawn_alacritty()
            self._send(200, b'ok'); return

        if u.path == '/notify-edit':
            slug = q.get('slug', [''])[0]
            if not slug:
                self._send(400, b'missing slug'); return
            LAST_SLUG[0] = slug
            self._send(200, b'ok'); return

        if u.path == '/current-slug':
            self._send(200, (LAST_SLUG[0] or '').encode()); return

        self._send(404, b''); return

    def _send(self, code, body):
        self.send_response(code)
        self.end_headers()
        if body:
            self.wfile.write(body)

    def end_headers(self):
        self.send_header('Access-Control-Allow-Origin', '*')
        super().end_headers()

    def log_message(self, *a):
        pass


HTTPServer(('127.0.0.1', PORT), Handler).serve_forever()
