#!/usr/bin/bash

_serve() {
  trap "kill 0" EXIT

  python3 -m http.server 1234 -d output &>/dev/null &

  while true; do 
    find $FORESTDIR/trees -type f | entr -rd $FORESTDIR/scripts/mkprivate
    sleep .5
  done

  wait
}

tmux new-session -d -s forest -n server "bash -c '$(declare -f _serve); _serve'"
